export enum ActionTriggers {
  CollectionView = 'collection-view',
  ItemView = 'item-view',
  LinkOpen = 'link-open',
  ItemDownload = 'item-download',
  ItemLike = 'item-like',
  ItemUnlike = 'item-unlike',
  ItemEmbed = 'item-embed',
  ItemSearch = 'item-search',
  Move = 'move',
  Create = 'create',
  Copy = 'copy',
  Update = 'update',
  Delete = 'delete',
  ChatCreate = 'chat_create',
  ChatUpdate = 'chat_update',
  ChatDelete = 'chat_delete',
  ChatClear = 'chat_clear',
  MemberLogin = 'member-login',
}
